In [1]:
import numpy as np

In [2]:
array = np.arange(1,11)

In [3]:
dim = array.ndim

In [4]:
dim

1

In [5]:
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
reshaped = array.reshape(5,2)

In [7]:
reshaped

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [8]:
new_dim = reshaped.ndim

In [9]:
new_dim

2

In [10]:
array = np.eye(4,dtype='float32')

In [11]:
print(array)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [12]:
array.dtype

dtype('float32')

In [13]:
#List to array conversion

In [14]:
a=[1,2,3]

In [15]:
b = np.asarray(a)

In [16]:
b

array([1, 2, 3])

In [17]:
#tuple to array

In [18]:
a=((1,2),(3,4))
b=np.asarray(a)
b

array([[1, 2],
       [3, 4]])

In [19]:
a=np.fromiter([1,2,3,4],dtype='int8')
b=np.fromiter((1,2,3,4),dtype='int8')
c=np.fromiter(range(1,5),dtype='int8')
d=np.fromiter('string',dtype='S50')

print("Array a is ",a)
print("Array b is ",b)
print("Array c is ",c)
print("Array d is ",d)

Array a is  [1 2 3 4]
Array b is  [1 2 3 4]
Array c is  [1 2 3 4]
Array d is  [b's' b't' b'r' b'i' b'n' b'g']


In [20]:
#Numerical ranges

In [21]:
marks = np.array([20,30,40])
# ID array
ids = np.linspace(0,4,3)

In [22]:
print(marks)
print(ids)

[20 30 40]
[0. 2. 4.]


In [23]:
a = np.arange(9)

In [24]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [25]:
a.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [26]:
#Slicing and indexing

In [27]:
array = np.array([3,4.5,3+5j,0])

In [28]:
real = np.isreal(array)

In [29]:
real

array([ True,  True, False,  True])

In [30]:
real_array = array[real]

In [31]:
real_array

array([3. +0.j, 4.5+0.j, 0. +0.j])

In [32]:
imag = np.iscomplex(array)

In [33]:
imag

array([False, False,  True, False])

In [34]:
imag_array = array[imag]

In [35]:
imag_array

array([3.+5.j])

In [36]:
#Vectorization

In [37]:
prices = np.array([[40, 35, 20], [21, 48, 70]])

In [38]:
prices = prices.flatten()

In [39]:
prices

array([40, 35, 20, 21, 48, 70])

In [40]:
buy_price = np.min(prices)

In [41]:
buy_price

20

In [42]:
index = list(prices).index(buy_price)

In [43]:
index

2

In [44]:
sell_price = np.max(prices)

In [45]:
sell_price

70

In [46]:
profit = sell_price - buy_price

In [47]:
profit

50

In [48]:
#Broadcasting

In [49]:
z = np.random.random((5,5))

In [50]:
z

array([[0.54965527, 0.62885657, 0.00980031, 0.14408179, 0.80277104],
       [0.59453472, 0.25314816, 0.06955199, 0.4486112 , 0.06766852],
       [0.13740338, 0.22910172, 0.84670565, 0.3033676 , 0.71156357],
       [0.71288828, 0.14945578, 0.54934107, 0.32299548, 0.52677059],
       [0.83146459, 0.14730388, 0.35412872, 0.86882382, 0.77716802]])

In [51]:
zmax = np.max(z)

In [52]:
zmin = np.min(z)

In [53]:
zmax

0.8688238165899885

In [54]:
zmin

0.009800310390976064

In [55]:
z_norm = (z-zmin)/(zmax-zmin)

In [56]:
z_norm

array([[0.62845191, 0.72065113, 0.        , 0.15631875, 0.92310714],
       [0.68069664, 0.28328427, 0.06955768, 0.51082524, 0.0673651 ],
       [0.14854433, 0.25529151, 0.97425196, 0.34174536, 0.81693138],
       [0.8184735 , 0.16257468, 0.62808614, 0.36459441, 0.60181157],
       [0.95650966, 0.16006962, 0.400837  , 1.        , 0.89330234]])

In [57]:
#---------------------------------------EXERciSE-------------------------------------------------------

In [58]:
coeff = np.array([1,-4,4])

In [59]:
roots = np.roots(coeff)

In [60]:
roots

array([2., 2.])

In [61]:
centigrade_temps = np.array([0, 10, 25, 32, 80, 99.99])

In [62]:
def convert(celsius):
    fahreinheit_temps = []
    return (1.8*celsius + 32)

In [63]:
fahreinheit_temps = convert(centigrade_temps)

In [64]:
fahreinheit_temps

array([ 32.   ,  50.   ,  77.   ,  89.6  , 176.   , 211.982])

In [65]:
A = np.array([[2,1,2],[3,0,1],[1,1,-1]])
b = np.array([[-3],[5],[2]])

In [66]:
b

array([[-3],
       [ 5],
       [ 2]])

In [67]:
A

array([[ 2,  1,  2],
       [ 3,  0,  1],
       [ 1,  1, -1]])

In [68]:
x = np.linalg.solve(A,b)

In [69]:
x

array([[ 2.5],
       [-3. ],
       [-2.5]])

In [70]:
check = np.allclose(np.dot(A,x), b)

In [71]:
check

True

In [72]:
B = np.array([[2,0,-1],[0,2,-1],[-1,0,1]])

In [73]:
I = np.identity(3)

In [74]:
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [75]:
A = 3*I-B

In [76]:
A

array([[1., 0., 1.],
       [0., 1., 1.],
       [1., 0., 2.]])